// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID               uuid.UUID
	ExecutedAt       time.Time
	Amount           string
	SenderAddress    uuid.UUID
	RecipientAddress uuid.UUID
}

type Wallet struct {
	Address   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Balance   string
}
