services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@db:5432/infotecs?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=infotecs
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d infotecs -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  pgdata: